### PR TITLE
Feature/fix error boundary event token destruction

### LINKED ISSUE #71: ErrorBoundary Event - Default Properties of the token object will deleted
#### Describe your issue
Consider the given process [error_boundary_test.txt](https://github.com/process-engine/process_engine/files/1950598/error_boundary_test.txt) .

If the token passes the `Throw no Error` task, the complete object structure of the token object gets replaced. 

In the normal case, the token object has a structure, which looks like: 
```
{
    current: {}, 
    history: {}
}
``` 

After the excecution of the Script Taskt, with the given Error boundary Event, the Token Object Structure looks like this:
```
{
    message: "",
    errorCode: ""
}
```

This Bug prevents the further access on the default token properties, such as `history`, and should not occur. 

#### How can others reproduce the issue?
* Create a Task
* Attach a `ErrorBoundaryEvent` to it
* Write a script task, that simply `console.log()` the token object (or any task, that tries to access the default token properties). 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by ElRaptorus**
Closes #71 

## What did you change?

Fix an Early-Exit issue that occured when using ErrorBoundaryEvents. 
These early exists caused the process to return as `finished`, even though there were still activities being performed.
This was due to the God-Class `NodeInstanceEntity`'s `end` method not handling these types of boundary events correctly.

This also explains (and fixes) the trouble we've had with the integrationtests for the ErrorBoundaryEvent.

Also applied another Boatload of TSLint fixes.

## How can others test the changes?

Run the tests located in process engine meta.

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.)
- [x] I've merged the `develop` branch into my branch before finishing this PR.
- [x] I've **not added any other changes** than the ones described above.
- [x] I've mentioned all **PRs, which relate to this one**

### CODE REVIEW

File: src/entity_types/node_instance.ts [hunk 1]
```diff
@@ -189,31 +188,45 @@ export class NodeInstanceEntity extends Entity implements INodeInstanceEntity {
...
     return role;
   }
 
   public async start(context: ExecutionContext, source: IEntity): Promise<void> {
 
-    debugInfo(`start node, id ${this.id}, key ${this.key}, type ${this.type}`);
+    logger.verbose(`start node, id ${this.id}, key ${this.key}, type ${this.type}`);
+
+    // check if context matches to lane
+    const role: string = await this.nodeDef.lane ? this.nodeDef.lane.role : undefined;
```
Comment (5ebastianMeier) [inline src/entity_types/node_instance.ts]: please remove this role check (the whole block)

**Comment by ElRaptorus** [comment]
@5ebastianMeier done
